# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  OUTPUT: ./stylesheets
  BASE: ./template.json
  BORDERLESS: ./template-borderless.json
  EXTENSION: ./extension.json

tasks:
  base:
    desc: Build base variant
    cmds:
      - bloom build {{.BASE}} --format rgb --plain -o {{.OUTPUT}}
    silent: true

  borderless:
    desc: [todo] Build borderless variant

  build:
    desc: Package files into importable flex archive
    deps: [base]
    cmds:
      -  zip -r rosepine-test.flex {{.OUTPUT}} {{.EXTENSION}}