# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BASEVARIANT: ./template.json
  BORDERLESS: ./template-borderless.json
  STYLESHEETS: ./stylesheets
  EXTENSION: ./extension.json
  FLEXBUILD: ./dist/rosepine-temp.flex

tasks:
  base:
    desc: Build base variant
    deps: [borderless]
    cmds:
      - bloom build {{.BASEVARIANT}} --format rgb --plain -o {{.STYLESHEETS}}
    silent: true

  borderless:
    desc: Build borderless variant
    cmds:
      - bloom build {{.BORDERLESS}} --format rgb --plain -o {{.STYLESHEETS}}
      - for file in {{.STYLESHEETS}}/*.json; do mv "$file" "${file%.json}-borderless.json"; done
    silent: true

  dawn-fix:
    desc: QuickFix dawn theme.
    deps: [base]
    cmds:
      - "sed -i 's/\"--on-primary\": \"rgba(87, 82, 121,1)\"/\"--on-primary\": \"rgba(250, 244, 237, 1)\"/' {{.STYLESHEETS}}/rose-pine-dawn.json"
      - "sed -i 's/\"--on-primary\": \"rgba(87, 82, 121,1)\"/\"--on-primary\": \"rgba(250, 244, 237, 1)\"/' {{.STYLESHEETS}}/rose-pine-dawn-borderless.json"

  build:
    desc: Package files into importable flex archive
    deps: [dawn-fix]
    cmds:
      -  zip -r {{.FLEXBUILD}} {{.STYLESHEETS}} {{.EXTENSION}}