# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BASEVARIANT: ./template.json
  BORDERLESS: ./template-borderless.json
  STYLESHEETS: ./stylesheets
  EXTENSION: ./extension.json
  FLEXBUILD: ./dist/rosepine-temp.flex

tasks:
  base:
    desc: Build base variant
    cmds:
      - bloom build {{.BASEVARIANT}} --format rgb --plain -o {{.STYLESHEETS}}
    silent: true

  base:dawn:
    desc: QuickFix dawn theme.
    deps: [base]
    cmds:
      - "sed -i 's/\"--on-primary\": \"rgba(87, 82, 121,1)\"/\"--on-primary\": \"rgba(250, 244, 237, 1)\"/' {{.STYLESHEETS}}/rose-pine-dawn.json"
      - "sed -i 's/\"--on-common-surface-variant\": \"rgba(40, 105, 131,1)\"/\"--on-common-surface-variant\": \"rgba(250, 244, 237, 1)\"/' {{.STYLESHEETS}}/rose-pine-dawn.json"

  borderless:
    desc: "[TODO] Build borderless variant"

  build:
    desc: Package files into importable flex archive
    deps: [base:dawn]
    cmds:
      -  zip -r {{.FLEXBUILD}} {{.STYLESHEETS}} {{.EXTENSION}}