name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Bump manifest file version from tag
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          jq --arg v "$VERSION" '.meta.version=$v' extension.json > tmp.json
          mv tmp.json extension.json

      - name: Install bloom
        run: |
          curl -L https://github.com/rose-pine/rose-pine-bloom/releases/download/v4.0.0/rose-pine-bloom-linux-amd64 -o bloom
          chmod +x bloom
          sudo mv bloom /usr/local/bin/

      - name: Run build
        run: make

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: "rosepine-*.flex"
